### ISSUE TITLE
请问你博客的代码高亮插件是哪个？

### ISSUE THREAD

**Issue by naah69** [titangene/titangene.github.io#1]
你博客的代码高亮效果很漂亮！
想问问你，你博客的代码高亮插件是哪个，我博客用的`highlight.js`，但是效果不是很好看
![image](https://user-images.githubusercontent.com/25682169/70375565-120f1f80-193a-11ea-896c-989e0e690979.png)

**Comment by titangene** [comment]
其實我用的也是 `highlight.js`，只是我自己改成喜歡的 highlight 主題，顏色是參考至 VS Code 的預設主題
blog 的原始碼我放在另一個 repo，你可以參閱看看：https://github.com/titangene/hexo-blog/blob/master/themes/material-flow/source/less/_highlight_vs2015.less

**Comment by naah69** [comment]
非常感谢，我已经修改完了！
[纳兰小筑](https://www.naah69.com)
